site_name: Nethereum
pages: 
- Home: 'index.md'
- Introduction:
    - 'Introduction' : 'introduction/introduction.md'
    - 'Getting started with the Ethereum Client' : 'introduction/ethereum-client.md'
    - 'Web3' : 'introduction/web3.md'
    - 'RPC' : 'introduction/rpc.md'
    - 'IPC' : 'introduction/ipc.md'
- Contracts:
    - 'Step by step writing contracts and deployment' : 'contracts/deploying.md'
    - 'DTO' : 'contracts/dto.md'
    - 'Calling' : 'contracts/calling.md'
    - 'Transactions' : 'contracts/transactions.md'
    - 'Events' : 'contracts/events.md'
    - 'Failing transactions' : 'contracts/failing-transactions.md'
